version: '3'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: guacamole-postgres
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - guacamole_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole_user -d guacamole_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Database Initialization Container
  init-db:
    image: postgres:14
    container_name: guacamole-init-db
    depends_on:
      - postgres
    volumes:
      - ./init/01-schema.sql:/schema/01-schema.sql
      - ./init/02-create-admin-user.sql:/schema/02-create-admin-user.sql
      - ./init/03-user-attribute.sql:/schema/03-user-attribute.sql
      - ./init/04-create-chrome-connection.sql:/schema/04-create-chrome-connection.sql
      - ./init/05-connection-attribute.sql:/schema/05-connection-attribute.sql
      - ./init/06-cleanup-duplicate-connections.sql:/schema/06-cleanup-duplicate-connections.sql
      - ./init/init-db.sh:/init-db.sh
    command: ["/bin/bash", "/init-db.sh"]
    networks:
      - guacamole_network
    restart: "no"
  # Guacamole Daemon (guacd)
  guacd:
    image: guacamole/guacd:1.5.0
    container_name: guacamole-daemon
    restart: always
    networks:
      - guacamole_network
    volumes:
      - ./config:/config
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4822"]
      interval: 10s
      timeout: 5s
      retries: 3
  # Chrome Browser with VNC
  chrome:
    image: consol/ubuntu-xfce-vnc:latest
    container_name: chrome
    hostname: chrome
    restart: always
    environment:
      - VNC_RESOLUTION=1280x720
      - VNC_PW=passwd
      - VNC_VIEW_ONLY=false
      - VNC_COL_DEPTH=24
    ports:
      - "5901:5901"  # VNC port
      - "6901:6901"  # noVNC port
    volumes:
      - chrome_data:/headless/Documents
    networks:
      - guacamole_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5901"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Add a small delay to ensure VNC server is fully started
    command: >
      bash -c "
        echo 'Starting Chrome VNC container...' &&
        sleep 10 &&
        /dockerstartup/vnc_startup.sh"
  # Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:1.5.0
    container_name: guacamole-web
    depends_on:
      - postgres
      - guacd
      - init-db
      - chrome
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      GUACAMOLE_HOME: /config
    volumes:
      - ./config:/config
    ports:
      - "5000:8080"
    restart: always
    networks:
      - guacamole_network
networks:
  guacamole_network:
    driver: bridge
volumes:
  postgres_data:
  chrome_data:
