version: '3'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: guacamole-postgres
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - guacamole_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole_user -d guacamole_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  
  # Guacamole Daemon (guacd)
  guacd:
    image: guacamole/guacd:1.5.0
    container_name: guacamole-daemon
    restart: always
    networks:
      - guacamole_network
    ports:
      - "4822:4822"
    volumes:
      - ./config:/config
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4822"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  # Chrome Browser with VNC
  chrome:
    image: consol/ubuntu-xfce-vnc:latest
    container_name: chrome
    hostname: chrome
    restart: always
    environment:
      - VNC_RESOLUTION=1280x720
      - VNC_PW=passwd
      - VNC_VIEW_ONLY=false
      - VNC_COL_DEPTH=24
    networks:
      - guacamole_network
    ports:
      - "5901:5901"
      - "6901:6901"
    volumes:
      - chrome_data:/headless/Documents
    # Modified healthcheck with longer start period and more retries
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f Xvnc || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 60s
    # Modified command to run VNC startup directly without sleep
    command: /dockerstartup/vnc_startup.sh
  
  # Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:1.5.0
    container_name: guacamole-web
    depends_on:
      postgres:
        condition: service_healthy
      guacd:
        condition: service_healthy
      chrome:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      GUACAMOLE_HOME: /config
    volumes:
      - ./config:/config
    networks:
      - guacamole_network
    ports:
      - "5000:8080"
    restart: always

networks:
  guacamole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres_data:
  chrome_data:
