version: '3'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: guacamole-postgres
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - guacamole_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole_user -d guacamole_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Database Initialization Container
  init-db:
    image: guacamole/guacamole:1.5.0
    container_name: guacamole-init-db
    depends_on:
      - postgres
    volumes:
      - ./init:/init
      - ./init:/schema
    command: >
      /bin/sh -c "
        echo 'Waiting for PostgreSQL to start...' &&
        sleep 20 &&
        /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql &&
        cat /init/01-schema.sql /init/02-create-admin-user.sql /init/03-user-attribute.sql /init/05-connection-attribute.sql /init/06-cleanup-duplicate-connections.sql > /init/combined.sql &&
        PGPASSWORD=guacamole_password psql -h postgres -U guacamole_user -d guacamole_db -f /init/combined.sql &&
        PGPASSWORD=guacamole_password psql -h postgres -U guacamole_user -d guacamole_db -f /init/04-create-chrome-connection.sql &&
        echo 'Database initialization completed'
      "
    networks:
      - guacamole_network
    restart: "no"
  
  # Guacamole Daemon (guacd)
  guacd:
    image: guacamole/guacd:1.5.0
    container_name: guacamole-daemon
    restart: always
    networks:
      - guacamole_network
    volumes:
      - ./config:/config
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4822"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  # Chrome Browser with VNC
  chrome:
    image: consol/ubuntu-xfce-vnc:latest
    container_name: chrome
    hostname: chrome
    restart: always
    environment:
      - VNC_RESOLUTION=1280x720
      - VNC_PW=passwd
      - VNC_VIEW_ONLY=false
      - VNC_COL_DEPTH=24
    networks:
      - guacamole_network
    volumes:
      - chrome_data:/headless/Documents
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5901"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Add a longer delay to ensure VNC server is fully started
    command: >
      bash -c "
        echo 'Starting Chrome VNC container...' &&
        sleep 45 &&
        /dockerstartup/vnc_startup.sh &&
        echo 'VNC server started and ready for connections' &&
        tail -f /dev/null"
  
  # Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:1.5.0
    container_name: guacamole-web
    depends_on:
      - postgres
      - guacd
      - init-db
      - chrome
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      GUACAMOLE_HOME: /config
    volumes:
      - ./config:/config
    networks:
      - guacamole_network
    ports:
      - "5000:8080"
    restart: always

networks:
  guacamole_network:
    name: guacamole_internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres_data:
  chrome_data:
