version: '3'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: guacamole-mysql
    environment:
      MYSQL_ROOT_PASSWORD: guacamole_root_password
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - guacamole_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Guacamole Daemon (guacd)
  guacd:
    image: guacamole/guacd:1.5.0
    container_name: guacamole-daemon
    restart: always
    networks:
      - guacamole_network
    volumes:
      - ./config:/config
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4822"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:1.5.0
    container_name: guacamole-web
    depends_on:
      mysql:
        condition: service_healthy
      guacd:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
    ports:
      - "8080:8080"
    restart: always
    networks:
      - guacamole_network

networks:
  guacamole_network:
    driver: bridge

volumes:
  mysql_data:
