version: '3'
services:
  # All-in-one Guacamole solution
  guacamole:
    image: linuxserver/guacamole:latest
    container_name: guacamole
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - GUACD_LOG_LEVEL=debug
    volumes:
      - guacamole_config:/config
    ports:
      - "5000:8080"
    restart: always

volumes:
  guacamole_config:
